---
title: "Griffiths et al 2015 survey results"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(reshape2)
library(plyr)
library(stringr)
#library(nlme)
library(MuMIn)
library(knitr)
library(captioner)
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

```{r captions, echo = FALSE}
table_nums <- captioner::captioner(prefix = "Table. ") #sets prefix for all tables
table_nums(name = "Table_2", caption = "Model selection results: Survey.", display = FALSE)

fig_nums <- captioner::captioner(prefix = "Figure.")
fig_nums(name = "Fig_1C", caption = "Smithora load at Eight sites in Choked Pass", display = FALSE)
```

```{r, echo=FALSE}
## load data
compare <- read.csv("../data/choked_seagrass_smithora.csv")
ang <- read.csv("../data/macrophyte_biomass_zeros_20170709.csv") # , stringsAsFactors=F
sites <- read.csv("../data/choked_sites.csv")
depths <- read.csv("../data/tides.morphos.Choked2015.csv")
```

```{r, echo=FALSE}
### compare
## from meadow surveys, identify edge and inner samples
edge <- filter(compare, site == "choked_edge_wolf")
inner <- filter(compare, site == "choked_inner_wolf")
compare_edge <- bind_rows(inner,edge)

###Making data nicer for plotting
#head(compare)
#View(compare)
compare_edge2 <- compare_edge
compare_edge2$site <- as.character(compare_edge2$site)
compare_edge2$site[compare_edge$site == "choked_edge_wolf"] <- "Edge"
compare_edge2$site <- as.character(compare_edge2$site)
compare_edge2$site[compare_edge$site == "choked_inner_wolf"] <- "Interior"

## function to estimate sds for boxplots
min.mean.sd.max <- function(x) {
  r <- c(min(x), mean(x) - sd(x), mean(x), mean(x) + sd(x), max(x))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}
```

FIGURE 1: SPATIAL TRENDS IN SMITHORA LOAD

```{r, echo=FALSE}
ang2 <- merge(ang, sites, by.x = "site", by.y = "name2")

## this next bit selects the sites we want, and removes a couple of rows that appeared to be duplicates, zeros, or unclearly assigned to a shoot. 
ang <- ang2 %>%
  filter(group != "kelp") %>%
  select(-c(notes, oven_date, QAQC_date,QAQC_Initials, Lat, Long, foil_wgt_g, wet_wgt_g, dry_wgt_g)) %>%
  mutate(uniqueID = paste(date, site, blade_sample_id, sep = ".")) %>%
  filter(final_dry_g != "0") %>%
  filter(final_dry_g > "0") %>%
  filter(uniqueID != "29-May.inner sandspit.75") %>%
  mutate(uniqueID2 = paste(uniqueID, final_dry_g, sep = ".")) %>%
  filter(uniqueID2 != "29-May.alcove.38.0.1") %>%
  select(-uniqueID2)

ang.smith <- subset(ang, ang$macrophyte %in% "smithora")
ang.zostera<- subset(ang, ang$macrophyte %in% "zostera")

ang4 <- merge(ang.smith, ang.zostera, by = c("blade_sample_id", "year","sample_time", "site", "distance_m"), all = TRUE)
ang5 <- ang4[,c("site", "group.y", "sample_time", "blade_sample_id", "distance_m", "macrophyte.x","final_dry_g.x", "macrophyte.y", "final_dry_g.y")]
ang5 <- ang4 %>%
  select(c(site, group.y, sample_time, blade_sample_id, distance_m, macrophyte.x,final_dry_g.x, macrophyte.y, final_dry_g.y)) %>%
  filter(macrophyte.y == "zostera") %>%
  replace_na(list(macrophyte.x = "smithora", final_dry_g.x = "0")) %>%
  mutate(ratio = as.numeric(final_dry_g.x) / final_dry_g.y)

ang5$ratio <- as.numeric(ang5$final_dry_g.x) / as.numeric(ang5$final_dry_g.y)
#ang5$date <- as.Date(ang5$date, format="%d-%b")
ang5$logratio <- log(ang5$ratio + 0.1)

ang5$non_zero <- ifelse(ang5$ratio > 0, 1, 0)

ang5$group.y <- revalue(ang5$group.y, c(edge = "Edge Sites", inner ="Interior Sites"))
ang5$site <- revalue(ang5$site, c("inner sandspit" = "IS", "outer sandspit" = "OS","inner tristan" = "IT", "inner ang" = "IA", "wolf" = "WF", "inner derek" = "ID", "alcove" = "AL", "inner carolyn" = "IC"))

ang6 <- merge(ang5, depths, by.x = "site", by.y = "Transect.Abbr")
ang5 <- ang6

summary<-ddply(ang5, .(site, sample_time, group.y), summarise, min(logratio))

site.summary<-ddply(ang5, .(site, sample_time, group.y), summarise, length(distance_m))
View(site.summary) #hist(log(ang5$ratio))

plot(ang5$site.depths.m ~ ang5$group.y)
```

Figure 1C: Smithora load in edge v interior sites  
```{r, echo=FALSE}
smith.load <- ggplot(ang5, aes(x = group.y, y = ratio)) + 
  geom_jitter(position = position_jitter(width=.2), size=3, colour = "gray60") +
  stat_summary(fun.data = min.mean.sd.max, geom = "boxplot", fill = "transparent") + 
  scale_y_continuous(name = "Smithora (g dwt) / Zostera (g dwt)", limits = c(-0.15, 4), breaks = c(0,1,2,3,4), labels = c(0,1,2,3,4)) + 
  theme_bw() + 
  theme(panel.grid = element_blank()) + 
  xlab(expression("Location")) + 
  geom_text(label = "C", x = 2.4, y = 4) +
  geom_text(label = "C", x = 2.4, y = 4) +
  theme(axis.title.x = element_text(vjust = -1, size = 12)) + 
  theme(axis.title.y = element_text(vjust = -1, size = 12))
#smith.load
ggsave("smith.load.ang.jpg", plot = smith.load, width = 3, height = 3)
```

## Analysis

```{r}
# model selection for smithora load
shapiro.test(ang5$logratio+0.01)
hist(ang5$logratio)
hist(ang5$ratio, breaks = 80)

#gamma hurdle models; this makes sense, but i'm flying solo on the random effects part.
m1 <- glm(non_zero ~ group.y*sample_time, data = ang5, family = binomial(link = logit))
m2 <- glm(ratio ~ group.y*sample_time, data = subset(ang5, non_zero == 1), family =Gamma(link = log))

(bin_coef <- plogis(coef(m1)[[1]]))
(gamma_coef <- exp(coef(m2)[[1]]))
(plogis(confint(m1)))
(exp(confint(m2)))


# this works too: See Sean Anderson's blog for interpretation. but this is i think the right way to go with the analyses; and will just take a bit more to plot the right estimates back on the figure but i'm close. 
library(lme4)
m1a <- glmer(non_zero ~ group.y*sample_time + (1|site), family = binomial(link = logit), verbose = 1, data = ang5)
m1b <- glmer(non_zero ~ group.y+sample_time + (1|site), family = binomial(link = logit), verbose = 1, data = ang5)
m1c <- glmer(non_zero ~ group.y + (1|site), family = binomial(link = logit), verbose = 1, data = ang5)
m1d <- glmer(non_zero ~ sample_time + (1|site), family = binomial(link = logit), verbose = 1, data = ang5)
m1e <- glmer(non_zero ~ group.y + site.depths.m + (1|site), family = binomial(link = logit), verbose = 1, data = ang5)
m1f <- glmer(non_zero ~ site.depths.m + (1|site), family = binomial(link = logit), verbose = 1, data = ang5)

model.sel(m1a, m1b, m1c, m1d, m1e, m1f)
coef1a <- as.data.frame(coef(m1a)$site[1:8, 1:4])
(bin_int <- plogis(coef1a[,1])) #make these values numeric
(bin_group.y <- plogis(coef1a[,2]))
(bin_sample_time <- plogis(coef1a[,3]))
(bin_gr.time <- plogis(coef1a[,4]))


m2a <- glmer(ratio ~ group.y*sample_time + (1|site), data = subset(ang5, non_zero == 1), family =Gamma(link = log))
m2b <- glmer(ratio ~ group.y + sample_time + (1|site), data = subset(ang5, non_zero == 1), family =Gamma(link = log))
m2c <- glmer(ratio ~ group.y + (1|site), data = subset(ang5, non_zero == 1), family =Gamma(link = log))
m2d <- glmer(ratio ~ sample_time + (1|site), data = subset(ang5, non_zero == 1), family =Gamma(link = log))
m2e <- glmer(ratio ~ group.y + site.depths.m + (1|site), data = subset(ang5, non_zero == 1), family =Gamma(link = log))
m2f <- glmer(ratio ~ group.y*sample_time + site.depths.m + (1|site), data = subset(ang5, non_zero == 1), family =Gamma(link = log))
m2g <- glmer(ratio ~ group.y + site.depths.m*sample_time + (1|site), data = subset(ang5, non_zero == 1), family =Gamma(link = log))
m2h <- glmer(ratio ~ site.depths.m*sample_time + (1|site), data = subset(ang5, non_zero == 1), family =Gamma(link = log))
model.sel(m2a, m2b, m2c, m2d, m2e, m2f, m2g, m2h)

(gamma_coef <- exp(coef(m2c)$site[1:8, 1]))
(exp(confint(m2)))

#detach('package:nlme', unload = TRUE)

#mod0 <- glmer(ratio ~ group.y*sample_time + (1|site), family = gamma, REML = FALSE, verbose = 1, data = ang5)
```

```{r}
#older analysis on log trasnformed data
ang5$site <- as.factor(ang5$site)
mod0 <- lme(I(log(ratio+0.01)) ~ group.y*sample_time, method = "ML", random = ~1|site, data = ang5)
mod1 <- lme(I(log(ratio+0.01)) ~ sample_time, method = "ML", random = ~1|site, data = ang5)
mod3 <- lme(I(log(ratio+0.01)) ~ group.y, method = "ML", random = ~1|site, data = ang5)
mod2 <- lme(I(log(ratio+0.01)) ~ 1,  method = "ML", random = ~1|site, data = ang5)
mod4 <- lme(I(log(ratio+0.01)) ~ group.y*sample_time, method = "ML", random = ~1 + sample_time|site, data = ang5)
smithora.summary <- model.sel(mod0, mod1, mod2, mod3, mod4)

mod4pr <- as.data.frame(predict(mod4))
colnames(mod4pr) <- c("mod4pr")
ang5$m4ratio <- exp(mod4pr)

```

`r fig_nums("Fig_1C")`

```{r Fig_1C Smith Load, fig.width=6, fig.height=3}
#hist(log(ang5$ratio+0.01))
## working on plotting raw data with backtransformed modeled coefficients for site, connecting lines by time.
## add code for more shape values

smith.load.date <- ggplot(ang5[(ang5$non_zero == "1"),], aes(x = factor(sample_time), y = ratio, group_by(group.y), shape = site)) + 
  geom_jitter(position = position_jitter(width=.2), colour = "grey75", size=2) +
  stat_summary(fun.data = min.mean.sd.max, geom = "boxplot", fill = "transparent") + 
  scale_y_continuous(name = "Smithora load (Smithora (g dwt) / Zostera (g dwt))", limits = c(0, 4), breaks = c(0,1,2,3,4), labels = c(0,1,2,3,4)) + 
  guides(size = FALSE) +
  scale_shape_manual(guide = guide_legend(title = "Site"), values = c(1,2,22,23,8,15,16,17)) +
  scale_x_discrete(labels = c("May", "June", "Aug")) +
  #geom_point(ang5, mapping = aes(sample_time, m4ratio$mod4pr, size = 2)) +
  theme_bw() + 
  theme(legend.key = element_rect(fill = NA), 
        axis.text = element_text(size = 8)) +
  facet_grid(cols = vars(group.y)) +
  theme(panel.grid = element_blank()) + 
  xlab(expression(" ")) + 
 # geom_text(label = "C", x = 2.4, y = 4) +
  theme(axis.title.x = element_text(vjust = -1, size = 10)) + 
  theme(axis.title.y = element_text(vjust = 3, size = 10))
smith.load.date

ggsave("Fig1C.smithload.jpg", plot = smith.load.date, width = 6, height = 3)
```



Monitoring data
(started with our data, but there isn't an inner site here, really...)

```{r}
shoots2015 <- read.csv("./data/biodiversitysurvey.2015.eelgrass.single.shoots.monitoring.csv")
shoots2015$site_id <- revalue(shoots2015$site, c("goose_east"="GsE", "goose_west"="GsW", "mcmullins_north" = "MMn", "mcmullins_south" = "MMs", "triquet_south" = "TqS", "triquet_north"= "TqN", "choked_south_pigu" = "Cspg", "choked_sandspit" = "Csan"))
#View(shoots2015)

shoots <- shoots2015 %>%
  filter(site_id %in% c("Csan", "Cspg")) %>%
  replace(is.na(.), 0) %>%
  mutate(sm.zm = smithora/total.dry.weight)

sm.zm <- ggplot(shoots, aes(x = site_id, y = sm.zm)) + 
  geom_point(size = 6, colour = "gray") +
  geom_boxplot(size = 1, fill = "transparent") + 
  scale_y_continuous(name = "Smithora / Zostera shoot weight (g/g dry wt)", limits = c(0, 2)) +
  theme_bw() + 
  theme(panel.grid = element_blank()) + 
  xlab(expression("Location")) + 
  geom_text(label = "A", x = 2.4, y = 15) +
  theme(axis.title.x = element_text(vjust = -1, size = 12)) + 
  theme(axis.title.y = element_text(vjust = -1, size = 12))
sm.zm
```

## Survey model results
`r table_nums("Table_S1.1")`

```{r Table_1, echo = FALSE}
kable(survey.mods, digits=2, align = 'c', col.names = c('Int','Zone','Date','Zone*Date', 'df', 'logLik','AICc','d','w'))
```


